### ISSUE TITLE
https://w3ctag.github.io/polyfills/ show raw text

### ISSUE THREAD

**Issue by azu** [w3ctag/polyfills#33]
Currently, https://w3ctag.github.io/polyfills/ show raw markdown text.
Is it expected behavior?

<img width="832" alt="image" src="https://user-images.githubusercontent.com/19714/104829622-decaee00-58b8-11eb-9ebb-c594dde736f7.png">

https://www.w3.org/Tools/respec/respec-w3c-common throw errors.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/19714/104829648-0cb03280-58b9-11eb-9001-131225b52727.png">

**Comment by cynthia** [comment]
It is absolutely not. As much as we love markdown, we didn't intend to expose it to that level to the public. Will look into this.

**Comment by tabatkins** [comment]
This document is still (or again?) broken in the same way again. It looks like maybe it's due to the contents being indented? Unsure if ReSpec's markdown support does something special for indented stuff that prevents it from being interpreted as code or not, but it looks like it might not.

In general, please do not publish raw ReSpec documents; in addition to problems like this, which I presume must have worked at some point, the general "flash of un-ReSpec'd content" problem is still annoying. Preprocess with ReSpec and publish the output, please.

**Comment by torgo** [comment]
this document is just fine and exists at https://www.w3.org/2001/tag/doc/polyfills/ - the canonical URL and the one that is linked from tag.w3.org.
